### ISSUE TITLE
JUPYTERHUB_API_TOKEN env is required to run jupyterhub-singleuser. Did you launch it manually?

### ISSUE THREAD

**Issue by mastermindankur** [bitnami/bitnami-docker-jupyter-base-notebook#3]
### Name and Version

bitnami/jupyter-base-notebook:latest

### What steps will reproduce the bug?

apple@apples-MacBook-Pro nodejs-hello-world % docker run --rm --name jupyter-base-notebook bitnami/jupyter-base-notebook:latest

### What is the expected behavior?

It should start a container.

### What do you see instead?
```
[I 2022-05-17 19:14:42.686 SingleUserLabApp mixins:614] Starting jupyterhub single-user server version 2.3.0
[I 2022-05-17 19:14:42.686 SingleUserLabApp mixins:629] Extending jupyterlab.labhubapp.SingleUserLabApp from jupyterlab 3.4.2
[I 2022-05-17 19:14:42.686 SingleUserLabApp mixins:629] Extending jupyter_server.serverapp.ServerApp from jupyter_server 1.17.0
[I 2022-05-17 19:14:42.731 SingleUserLabApp manager:340] jupyterlab | extension was successfully linked.
[I 2022-05-17 19:14:42.746 SingleUserLabApp manager:340] nbclassic | extension was successfully linked.
[I 2022-05-17 19:14:42.962 SingleUserLabApp manager:340] notebook_shim | extension was successfully linked.
JUPYTERHUB_API_TOKEN env is required to run jupyterhub-singleuser. Did you launch it manually?
```

**Comment by rafariossaa** [comment]
Hi,
  This container image needs some parameters. Maybe you can take a look how it is used[ in the chart](https://github.com/bitnami/charts/tree/master/bitnami/jupyterhub).

**Comment by mastermindankur** [comment]
Thank you, i tried adding environment variables and added JUPYTERHUB_API_TOKEN as one of them and experimented with multiple permutations.

docker run -e JUPYTERHUB_API_TOKEN=xx -e OAUTH_CLIENT_ID=mastermindankur -e OAUTH_CLIENT_SECRET=yy --rm --name jupyter-notebook bitnami/jupyter-base-notebook

However I could not find the documentation - which environment variables it expects.


Traceback (most recent call last):
  File "/opt/bitnami/miniconda/bin/jupyterhub-singleuser", line 8, in <module>
    sys.exit(main())
  File "/opt/bitnami/miniconda/lib/python3.7/site-packages/jupyterhub/singleuser/app.py", line 66, in main
    return SingleUserLabApp.launch_instance()
  File "/opt/bitnami/miniconda/lib/python3.7/site-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/opt/bitnami/miniconda/lib/python3.7/site-packages/traitlets/config/application.py", line 964, in launch_instance
    app.initialize(argv)
  File "/opt/bitnami/miniconda/lib/python3.7/site-packages/jupyterhub/singleuser/mixins.py", line 929, in initialize
    result = super().initialize(*args, **kwargs)
  File "/opt/bitnami/miniconda/lib/python3.7/site-packages/jupyterhub/singleuser/mixins.py", line 637, in initialize
    return super().initialize(argv)
  File "/opt/bitnami/miniconda/lib/python3.7/site-packages/traitlets/config/application.py", line 107, in inner
    return method(app, *args, **kwargs)
  File "/opt/bitnami/miniconda/lib/python3.7/site-packages/jupyter_server/serverapp.py", line 2414, in initialize
    self.init_webapp()
  File "/opt/bitnami/miniconda/lib/python3.7/site-packages/jupyterhub/singleuser/mixins.py", line 674, in init_webapp
    self.init_hub_auth()
  File "/opt/bitnami/miniconda/lib/python3.7/site-packages/jupyterhub/singleuser/mixins.py", line 670, in init_hub_auth
    raise ValueError("Missing OAuth client ID")
ValueError: Missing OAuth client ID

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, but these jupiterhubs containers are created to be used in [this chart](https://github.com/bitnami/charts/tree/master/bitnami/jupyterhub). If you want to use it not in the chart, I would suggest you to take a look to the official jupyterhub documentation on how to proper configure it.

**Comment by mastermindankur** [comment]
thank you @rafariossaa , yes i tried the parameters in the chart, but was unable to run the image as a container. I tried many permutations and combinations but it still fails. If some one may have been able to run this image and can share the docker command or yaml file - will be great, will put it in the documentation.

**Comment by rafariossaa** [comment]
Hi,
  Let's wait and see if someone else can help with this.
